language: rust
cache: cargo
sudo: false
git:
  depth: 10
script:
  - cargo build --verbose
  - cargo test --verbose
rust:
  - nightly
  - beta
  - stable
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
