#!/bin/sh

set -ex

cd graphql-idl-parser-ffi

cargo update
cargo build
gcc -O3 -DDEBUG -o example/example example/example.c -std=c11 -Wextra -Wall -pedantic -Werror -Wfatal-errors -Wstrict-aliasing -Iincludes -Ltarget/debug -lgraphqlidlparser

./example/example
