#!/bin/sh

set -ex

test_dir=$(pwd)/test

cd graphql-idl-parser-ffi

lib_dir=$(pwd)/target/debug

cargo update
cargo build

cd test

python generate.py .

gcc -I. -I../includes -L$lib_dir -lgraphqlidlparser clar.c main.c helpers.c scalars.c objects.c enums.c interfaces.c unions.c input_objects.c -o gql-idl-parser-test -DCLAR_FIXTURE_PATH=\"$test_dir\"

./gql-idl-parser-test

# valgrind --leak-check=full --dsymutil=yes --error-exitcode=1 ./gql-idl-parser-test  >/dev/null
